package insilico.vega.gui;

import insilico.core.molecule.InsilicoMolecule;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import insilico.core.molecule.tools.Depiction;
import org.openscience.cdk.exception.CDKException;
import org.openscience.cdk.interfaces.IAtomContainer;
//import org.openscience.cdk.interfaces.IMolecule;
import org.openscience.cdk.layout.StructureDiagramGenerator;
import org.openscience.cdk.renderer.AtomContainerRenderer;
import org.openscience.cdk.renderer.font.AWTFontManager;
import org.openscience.cdk.renderer.generators.BasicAtomGenerator;
import org.openscience.cdk.renderer.generators.BasicSceneGenerator;
import org.openscience.cdk.renderer.generators.IGenerator;
import org.openscience.cdk.renderer.generators.RingGenerator;
import org.openscience.cdk.renderer.visitor.AWTDrawVisitor;

/**
 *
 * @author User
 */
public class PanelMolViewer extends javax.swing.JPanel {

    private InsilicoMolecule CurMol; // as smiles

    
    /**
     * Creates new form PanelMolViewer
     */
    public PanelMolViewer() {
        CurMol = null;
        initComponents();
    }


    public void SetMolecule(InsilicoMolecule mol) {
        CurMol = mol;
        this.repaint();
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (CurMol == null) {
            
            try {

                Graphics2D g2D = (Graphics2D) g;

                // Builds the Image object
                g2D.setBackground(Color.WHITE);
                //g2D.clearRect(0, 0, this.getWidth(), this.getHeight());

            } catch (Throwable e) {
//                InsilicoLogger.getLogger().warn("Unable to paint on molecule viewer - " + e.getMessage());
            }            
            return;
        }
        
        try {
            
            // Generates structure
            StructureDiagramGenerator sdg = new StructureDiagramGenerator();
            sdg.setMolecule(CurMol.GetStructure());
            try {
                sdg.generateCoordinates();
            } catch (CDKException e) { 
                throw new Exception("Unable to generate coordinates for molecule");        
            }

            IAtomContainer mol = sdg.getMolecule();

            // Create image generators
            List<IGenerator<IAtomContainer>> generators = new ArrayList<IGenerator<IAtomContainer>>();
            generators.add(new BasicSceneGenerator());
            generators.add(new RingGenerator());
            generators.add(new BasicAtomGenerator());

            // the renderer needs to have a toolkit-specific font manager 
            AtomContainerRenderer renderer = new AtomContainerRenderer(generators, new AWTFontManager());

            Graphics2D g2D = (Graphics2D) g;
            
            // the call to 'setup' only needs to be done on the first paint
            Rectangle drawArea = new Rectangle(this.getWidth(), this.getHeight());
            renderer.setup(mol, drawArea);

            Rectangle diagramBounds = renderer.calculateDiagramBounds(mol);
            renderer.setZoomToFit(drawArea.width, drawArea.height, diagramBounds.width, diagramBounds.height);

            // Builds the Image object
            g2D.drawImage(Depiction.DepictMolecule(mol, this.getWidth(), this.getHeight()), 0, 0 , null);
            g2D.setBackground(Color.WHITE);
//            g2D.clearRect(0, 0, this.getWidth(), this.getHeight());
            g2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);
            g2D.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
            g2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2D.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
            g2D.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_LCD_HRGB);
            g2D.dispose();


            renderer.paint(mol, new AWTDrawVisitor(g2D));

        } catch (Exception e) {
//            InsilicoLogger.getLogger().warn("Unable to paint on molecule viewer - " + e.getMessage());
        }
        
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
