package insilico.vega.gui;

import insilico.vega.gui.models.VegaModelsWrapper;
import javax.swing.JFrame;
import javax.swing.SpringLayout;
import layout.SpringUtilities;

/**
 *
 * @author Alberto
 */
public class PanelModelList extends javax.swing.JPanel {

    private final PanelEndpointGroup[] EpPanels;
    private final JFrame Parent;
    private final VegaModelsWrapper Endpoints;
       
    /**
     * Creates new form PanelModelList
     */
    public PanelModelList(JFrame Parent, VegaModelsWrapper ModelsList) {        
        this.Parent = Parent;
        this.Endpoints = ModelsList;
        initComponents();                
        
        jPanelModels.setOpaque(true);
        jPanelModels.setLayout(new SpringLayout());
        
        // Filter
        jComboFilter.removeAllItems();
        jComboFilter.addItem("All available endpoints");
        for (int i=1; i<VegaModelsWrapper.SECTION_NAMES.length; i++)
            jComboFilter.addItem(VegaModelsWrapper.SECTION_NAMES[i]);        
        
        // Prepare all EP panels
        EpPanels = new PanelEndpointGroup[Endpoints.Endpoints.size()];
        int idx = 0;
        for (VegaModelsWrapper.VegaEndpoint EP : Endpoints.Endpoints)  {
            EpPanels[idx] = new PanelEndpointGroup(EP);
            idx++;
        }
        
        PutAndShowEndpointPanels(0);        
    }

    
    private void PutAndShowEndpointPanels(int filter) {
        
        // Init panel with list of endpoints
        jPanelModels.removeAll();
        jPanelModels.setLayout(new SpringLayout());

        int nPanels = 0;
        
        for (PanelEndpointGroup panel : EpPanels) {
            if ( (filter == 0) || (panel.Group == filter)) {
                jPanelModels.add(panel);
                nPanels++;
            }
        }
        
        SpringUtilities.makeCompactGrid(jPanelModels, 
                                nPanels, 1, //rows, cols
                                4, 4,          //initX, initY
                                4, 4);         //xPad, yPad        
       
        this.validate();
    }
    
    private void UpdateFilter() {
        if (EpPanels == null)
            return;
        
        int filter = jComboFilter.getSelectedIndex();
        PutAndShowEndpointPanels(filter);

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrapper = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelModels = new javax.swing.JPanel();
        jPanelChoice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboFilter = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));

        jPanelModels.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelModelsLayout = new javax.swing.GroupLayout(jPanelModels);
        jPanelModels.setLayout(jPanelModelsLayout);
        jPanelModelsLayout.setHorizontalGroup(
            jPanelModelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanelModelsLayout.setVerticalGroup(
            jPanelModelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelModels);

        javax.swing.GroupLayout jPanelWrapperLayout = new javax.swing.GroupLayout(jPanelWrapper);
        jPanelWrapper.setLayout(jPanelWrapperLayout);
        jPanelWrapperLayout.setHorizontalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanelWrapperLayout.setVerticalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        jPanelChoice.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Filter models:");

        jComboFilter.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboFilterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelChoiceLayout = new javax.swing.GroupLayout(jPanelChoice);
        jPanelChoice.setLayout(jPanelChoiceLayout);
        jPanelChoiceLayout.setHorizontalGroup(
            jPanelChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelChoiceLayout.setVerticalGroup(
            jPanelChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboFilterItemStateChanged
        UpdateFilter();
    }//GEN-LAST:event_jComboFilterItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelChoice;
    private javax.swing.JPanel jPanelModels;
    private javax.swing.JPanel jPanelWrapper;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
