debug=true
appender.0.type = Console
appender.0.name = CONSOLE
appender.0.layout.type = PatternLayout
appender.0.layout.pattern=%d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n

appender.1.type=RollingFile
appender.1.name=FILE
appender.1.fileName=${sys:user.home}/vega/logs/vega.log
appender.1.filePattern=${sys:user.home}/vega/logs/vega-%d{yyyy-MM-dd-HH}.log.gz
appender.1.layout.type=PatternLayout
appender.1.layout.pattern=%d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.1.policies.type = Policies
appender.1.policies.size.type = SizeBasedTriggeringPolicy
appender.1.policies.size.size = 1MB

rootLogger.level = INFO
rootLogger.appenderRef.0.ref = CONSOLE
rootLogger.appenderRef.1.ref = FILE